dist: trusty
language: c
compiler:
  - gcc

install:
  - sudo apt-get install lcov rubygems-integration
  - gem install lcoveralls

before_script:
  - ./build.sh build

script:
  - ./build.sh test

after_success:
  - cd build
  - lcoveralls
