dist: trusty
language: c
compiler:
  - gcc
  - clang

env:
  global:
    secure: lx7a1oLm9h44SCwgQJkUYTstBSw2lblseOftY37s7LFgZmFojC/qWsR8PVecdxYz0v5pYSqYZkH2tRRNLAaUFDaiP4vcT/m+KXLG4+M1RUlJEjYnau4XIvpBoP7Bos3Gjf30RcR+ocbY+7gastE6cLYgqyVN3ewfwvVFdaH0KIi9E17l1z2KbHK+WkS7jhIWEGLoundGxm9Vxby30fQeypLbNKPAxMW0W/Tpgx3YEMQ6aQr92sKzB7USHqoT0rtUXkEslL27NEr2UiBS78PREHIQdQfBxEImaQQPZl68RoBxhxgpD6TdqMjPWxQ9GlGF0S7akmtJ/MKOa5h+6y0ByZ9ZakG6jPcNDnhBT/lZD3qPLkTn/H4JmukXfocLn/18XaeSxlzvbCHaeTSIr3F39MpfzsQ3Le7I/f/mLSNoexGnyEZhgO8LIKWaMXMhPedVrkhgBmySVIsxn5J7rv3isJIAIORcOze84WRnVdKrGgifCeMN1IXK5+Odb58PJ33/GD0qXEe/Os5B9ckX5OeBNJtFmIecZN/CrCzC6DvYvyf2EFrTUSm+d58rYCZpKV8t55qRPGEsy2J75x8Sye9VDsGHQwf1sA81v93Dsf8QS4B2vdIzI6tXXBLvg59h0b2k/eADEswEFPWCS+umXyhL2hkxFGUF9VlEeG4+SZU7Zgs=

install:
  - pip install --user cpp-coveralls

before_script:
  - "./build.sh build"

script:
  - "./build.sh test"

after_success:
  - coveralls
